name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g @lhci/cli@0.8.x
      - run: sudo apt-get install ruby-full build-essential zlib1g-dev
      - run: sudo gem install jekyll bundler
      - run: sudo bundle install
      - run: sudo bundle exec jekyll build
      - run: lhci autorun